included:
  - Sources
  - ./Package.swift
disabled_rules:
  - todo
  - function_body_length
line_length:
  warning: 170
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

