name: Build

on: 
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest 

    steps: 
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build
        run: swift build -v
