name: SwiftLint

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  swiftlint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
